# XD on YARN deployment configuration
xd:
    adminServers: 1
	adminMemory: 512M
    containers: 3
	containerMemory: 512M
    container:
        groups: yarn

spring:
    yarn:
        applicationDir: /xd/app/

# Port that admin-ui is listening on
#server:
#    port: 9393

---

# Hadoop configuration
#spring:
#    hadoop:
#        fsUri: hdfs://localhost:8020
#        resourceManagerHost: localhost

---

# XD data transport (default is redis)
#xd:
#    transport: rabbit

---

# YARN classpath settings -- in the next Spring XD release we hope to make this more auto-configured, but for now we need to provide the
# classpath that each distro uses for "yarn.application.classpath" and it should also include "mapreduce.application.classpath".
# Just comment out the ones not needed and make sure the one for your current distro is not commented out. These settings are based
# on single-node VMs provided for each distro and they might need tweaking for other installation types.

# Hadoop 2.2.0 (hadoop22):
spring:
    yarn:
        siteYarnAppClasspath: "$HADOOP_CONF_DIR,$HADOOP_COMMON_HOME/share/hadoop/common/*,$HADOOP_COMMON_HOME/share/hadoop/common/lib/*,$HADOOP_HDFS_HOME/share/hadoop/hdfs/*,$HADOOP_HDFS_HOME/share/hadoop/hdfs/lib/*,$HADOOP_YARN_HOME/share/hadoop/yarn/*,$HADOOP_YARN_HOME/share/hadoop/yarn/lib/*"
        siteMapreduceAppClasspath: "$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*,$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*"

# Pivotal HD 2.0 (phd20):
#spring:
#    yarn:
#        siteYarnAppClasspath: "$HADOOP_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_HDFS_HOME/*,$HADOOP_YARN_HOME/*"
#        siteMapreduceAppClasspath: "$HADOOP_MAPRED_HOME/*,$HADOOP_MAPRED_HOME/lib/*"

# Hortonworks HDP 2.1 (hdp21):
#spring:
#    yarn:
#        siteYarnAppClasspath: "/etc/hadoop/conf,/usr/lib/hadoop/*,/usr/lib/hadoop/lib/*,/usr/lib/hadoop-hdfs/*,/usr/lib/hadoop-hdfs/lib/*,/usr/lib/hadoop-yarn/*,/usr/lib/hadoop-yarn/lib/*"
#        siteMapreduceAppClasspath: "/usr/lib/hadoop-mapreduce/*,/usr/lib/hadoop-mapreduce/lib/*"

# Cloudera CDH5 (cdh5):
#spring:
#    yarn:
#        siteYarnAppClasspath: "$HADOOP_CLIENT_CONF_DIR,$HADOOP_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*"
#        siteMapreduceAppClasspath: "$HADOOP_MAPRED_HOME/*,$HADOOP_MAPRED_HOME/lib/*"

---
# Zookeeper properties
# client connect string: host1:port1,host2:port2,...,hostN:portN
#zk:
#  client:
#     connect: localhost:2181

---
# Redis properties
#spring:
#  redis:
#   port: 6379
#   host: localhost

---
# RabbitMQ properties
#spring:
#  rabbitmq:
#   host: localhost
#   port: 5672
#   username: guest
#   password: guest
#   virtual_host: /

---
#Disable batch database initialization
#spring:
#  batch:
#    initializer:
#       enabled: false

---
# Database settings
#
# Config for use with HSQLDB
#spring:
#  datasource:
#    url: jdbc:hsqldb:hsql://localhost:9101/xdjob
#    username: sa
#    password:
#    driverClassName: org.hsqldb.jdbc.JDBCDriver

# Config for use with MySQL - uncomment and edit with relevant values for your environment
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/xdjob
#    username: yourUsername
#    password: yourPassword
#    driverClassName: com.mysql.jdbc.Driver
#  profiles:
#    active: default,mysql

# Config for use with Postgres - uncomment and edit with relevant values for your environment
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/xdjob
#    username: yourUsername
#    password: yourPassword
#    driverClassName: org.postgresql.Driver
#  profiles:
#    active: default,postgresql
