spring:
    yarn:
        appmaster:
            appmasterClass: org.springframework.yarn.am.StaticEventingAppmaster
            containerCount: 1
            keepContextAlive: false
            launchcontext:
                useYarnAppClasspath: true
                useMapreduceAppClasspath: true
            localizer:
                patterns:
                    - "spring-xd-yarn*.zip"
                    - "servers.yml"
                    - "modules.yml"
                    - "custom-modules.zip"
---
spring:
    profiles: admin
    yarn:
        appName: xd-admin
        appmaster:
            resource:
                memory: ${xd.containerMemory:512M}
            launchcontext:
                runnerClass: org.springframework.xd.dirt.server.AdminServerApplication
                arguments:
                    -Dspring.application.name: "admin"
                    -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                    -Dspring.config.location: "./servers.yml"
                    -Dxd.module.config.location: "file:./"
                containerAppClasspath:
                    - "./${spring.xd.yarn.app.zip}/config"
                    - "./${spring.xd.yarn.app.zip}/lib/*"
                    - "./custom-modules.zip"
---
spring:
    profiles: container
    yarn:
        appName: xd-container
        appmaster:
            resource:
                memory: 512M
            launchcontext:
                runnerClass: org.springframework.xd.dirt.server.ContainerServerApplication
                arguments:
                    -Dspring.application.name: "container"
                    -DxdHomeDir: "./${spring.xd.yarn.app.zip}"
                    -Dspring.config.location: "./servers.yml"
                    -Dxd.module.config.location: "file:./"
                containerAppClasspath:
                    - "./${spring.xd.yarn.app.zip}/config"
                    - "./${spring.xd.yarn.app.zip}/lib/*"
                    - "./${spring.xd.yarn.app.zip}/modules/processor/scripts"
                    - "./custom-modules.zip/modules/processor/scripts"
                    - "./custom-modules.zip"
